### ISSUE TITLE
use the silent interface implementations instead of those from the data module

### ISSUE THREAD

**Issue by egonw** [PistoiaHELM/ChemistryToolkitCDK#2]
Replace things like:

    import org.openscience.cdk.Atom;

with

    import org.openscience.cdk.silent.Atom;

This change will speed up your code with some 10%...

(Unless you depend on getting change notification messages...)

**Comment by MarkusWeisser** [comment]
Thank you very much for your comment. 
Now the silent interface implementations are used

**Comment by egonw** [comment]
Did you measure how much faster it is for your situation / code base?

**Comment by MarkusWeisser** [comment]
Well, performance measurements are currently not planned in this direction. However, it is always good to know that we are using the library with optimum speed.
